project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Laeeq Ur Rehman"
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About

  page-footer:
    center: "Copyright © 2025 Laeeq"

  favicon: /favicon.png

format:
  html:
    theme:
      light: flatly  
      dark: darkly    
    css: styles.css  

    toc: true









