project:
  type: website
  output-dir: docs

website:
  title: "Laeeq Ur Rehman"
  navbar:
    logo: /favicon.png
    title-href: index.qmd
    right:
      - icon: file-earmark-person
        href: Laeeq_CV.pdf
        text: "CV"
      - icon: list-check
        href: Skills.qmd
        text: "Skills"
      - text: Projects
        menu:
          - icon: laptop
            href: projects/personal.qmd
            text: "Personal Projects"
          - icon: mortarboard
            href: projects/academic.qmd
            text: "Academic Projects"
      - icon: award
        href: achievements.html
        text: "Achievements"
      - icon: compass
        href: Future.qmd
        text: "Future Plans"
      - icon: person
        href: about.qmd
        text: "About"


  page-footer:
    center: "Copyright © 2025 Laeeq"

  favicon: /favicon.png

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css:
      - styles.css
      - custom.scss
    toc: true
