project:
  type: website
  output-dir: docs

website:
  title: "Laeeq Ur Rehman"
  navbar:
    logo: /favicon.png  # Optional: add a small icon to the left of your name
    title-href: index.qmd  # ✅ Makes title clickable to home
    left:
      # Home is removed from here
      - href: cv.qmd
        text: CV
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About

  page-footer:
    center: "Copyright © 2025 Laeeq"

  favicon: /favicon.png

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css:
      - styles.css
      - custom.scss
    toc: true










