project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Laeeq-1.github.io"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hello.qmd

  page-footer:
   center: "Copyright © 2025 Laeeq"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

    








