project:
  type: website
  output-dir: docs

website:
 page-footer:
  center: "Copyright © 2025 Laeeq"
  navbar:
    title: "Laeeq-1.github.io"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hello.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    
    








